baseurl = "http://itprom.info"
title = "ITProm 2018 - Outer Space"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[permalinks]
    posts = "posts/:title/"
    default = ":title/"

[params]
    author = "ITProm 2018"
    description = "John Doe's personal website"
    keywords = "blog,developer,personal"
    info = "Outer Space"

[[params.social]]
    name = "Information"
    weight = 1
    url = "/information"
[[params.social]]
    name = "Prom Court"
    weight = 2
    url = "/prom_court"
[[params.social]]
    name = "Promposal Contest"
    weight = 3
    url = "/promposal_contest/"
[[params.social]]
    name = "Questions?"
    weight = 4
    url = "/questions/"

[[menu.main]]
    name = "Information"
    weight = 1
    url = "/information"
[[menu.main]]
    name = "Prom Court"
    weight = 2
    url = "/prom_court"
[[menu.main]]
    name = "Promposal Contest"
    weight = 3
    url = "/promposal_contest/"
[[menu.main]]
    name = "Questions?"
    weight = 4
    url = "/questions/"
